# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.12
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: gbrielbbarn@gmail.com
author_name: Gabriel Barn
preset_name: starter
project_name: SRANS-FrontEnd

